/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ComposeRouteImport } from './routes/compose'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookNoIndexRouteImport } from './routes/$bookNo.index'
import { Route as BookNoChapterNoRouteImport } from './routes/$bookNo.$chapterNo'

const ComposeRoute = ComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookNoIndexRoute = BookNoIndexRouteImport.update({
  id: '/$bookNo/',
  path: '/$bookNo/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookNoChapterNoRoute = BookNoChapterNoRouteImport.update({
  id: '/$bookNo/$chapterNo',
  path: '/$bookNo/$chapterNo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compose': typeof ComposeRoute
  '/$bookNo/$chapterNo': typeof BookNoChapterNoRoute
  '/$bookNo/': typeof BookNoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compose': typeof ComposeRoute
  '/$bookNo/$chapterNo': typeof BookNoChapterNoRoute
  '/$bookNo': typeof BookNoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compose': typeof ComposeRoute
  '/$bookNo/$chapterNo': typeof BookNoChapterNoRoute
  '/$bookNo/': typeof BookNoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/compose' | '/$bookNo/$chapterNo' | '/$bookNo/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compose' | '/$bookNo/$chapterNo' | '/$bookNo'
  id: '__root__' | '/' | '/compose' | '/$bookNo/$chapterNo' | '/$bookNo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComposeRoute: typeof ComposeRoute
  BookNoChapterNoRoute: typeof BookNoChapterNoRoute
  BookNoIndexRoute: typeof BookNoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/compose': {
      id: '/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof ComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$bookNo/': {
      id: '/$bookNo/'
      path: '/$bookNo'
      fullPath: '/$bookNo/'
      preLoaderRoute: typeof BookNoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$bookNo/$chapterNo': {
      id: '/$bookNo/$chapterNo'
      path: '/$bookNo/$chapterNo'
      fullPath: '/$bookNo/$chapterNo'
      preLoaderRoute: typeof BookNoChapterNoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComposeRoute: ComposeRoute,
  BookNoChapterNoRoute: BookNoChapterNoRoute,
  BookNoIndexRoute: BookNoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
