/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookNoChapterNoRouteImport } from './routes/$bookNo.$chapterNo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookNoChapterNoRoute = BookNoChapterNoRouteImport.update({
  id: '/$bookNo/$chapterNo',
  path: '/$bookNo/$chapterNo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$bookNo/$chapterNo': typeof BookNoChapterNoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$bookNo/$chapterNo': typeof BookNoChapterNoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$bookNo/$chapterNo': typeof BookNoChapterNoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$bookNo/$chapterNo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$bookNo/$chapterNo'
  id: '__root__' | '/' | '/$bookNo/$chapterNo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookNoChapterNoRoute: typeof BookNoChapterNoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$bookNo/$chapterNo': {
      id: '/$bookNo/$chapterNo'
      path: '/$bookNo/$chapterNo'
      fullPath: '/$bookNo/$chapterNo'
      preLoaderRoute: typeof BookNoChapterNoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookNoChapterNoRoute: BookNoChapterNoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
